### ISSUE TITLE
Typo in your slide, playtime 7

### ISSUE THREAD

**Issue by PaulineBodson** [reinhrst/nitwit2gitwit#5]
Hi Claude, 
I wanted to signal you a typo in your slide number 3.1 from the playtime 7. 
You wrote " Conflict can only every happen when doing merge or rebase". 
I guess you wanted to say " Conflict can only **ever** happen when doing merge or rebase". 

Here is the link to the slide:
[https://n2g.claude-apps.com/lessons/7/playtime.html#/how-to-create-conflicts](url)

**Comment by PaulineBodson** [comment]
@reinhrst I need to state an issue on my previous comment, the link is not sending you to the slide in question. 
I activated the "link" logo (the 6th logo starting from the left, when writing in the message box). I added my link inside but it seems to be sending me back to the issue page. 
Here, is the link I wanted to share: https://n2g.claude-apps.com/lessons/7/playtime.html#/how-to-create-conflicts

**Comment by reinhrst** [comment]
@PaulineBodson nice, thanks :).

BTW, with the markdown (what this is) you can make links in two ways

```markdown
[Here can be the link text)[https://n2g.claude-apps.com/lessons/7/playtime.html#/how-to-create-conflicts]
or if you just want the link itself in the text <https://n2g.claude-apps.com/lessons/7/playtime.html#/how-to-create-conflicts>
```

Now Github also makes a link of anything you put in the text which looks like a link (like https://www.claude.nl/) -- this is nice, but not always what you want. In Quarto it only becomes a link if you put it within `<>`.
